import type { TreeNode } from "@/components/FolderTree";

const f = (name: string, children: TreeNode[]): TreeNode => ({
  name,
  type: "folder",
  children,
});
const file = (name: string): TreeNode => ({ name, type: "file" });

export const tree: TreeNode = f("blessride/", [
  f(".github", [
    f("workflows", [
      file("ci.yml"),
      file("cd.yml"),
      file("preview.yml"),
    ]),
    file("PULL_REQUEST_TEMPLATE.md"),
    file("CODEOWNERS"),
  ]),
  f("public", [
    file("favicon.svg"),
    file("logo.svg"),
    file("manifest.json"),
    file("robots.txt"),
  ]),
  f("docs", [
    file("ARCHITECTURE.md"),
    file("API_CONTRACTS.md"),
    file("DEPLOYMENT.md"),
    file("SECURITY.md"),
    file("ACCESSIBILITY.md"),
    file("CONTRIBUTING.md"),
    f("diagrams", [
      file("system-overview.drawio"),
      file("data-model.drawio"),
      file("ride-flow.drawio"),
    ]),
  ]),
  f("functions", [
    file("package.json"),
    file("tsconfig.json"),
    file(".eslintrc.json"),
    f("src", [
      file("index.ts"),
      f("auth", [
        file("onUserCreate.ts"),
        file("onUserDelete.ts"),
        file("setCustomClaims.ts"),
        file("verifyPhoneOtp.ts"),
      ]),
      f("rides", [
        file("createRide.ts"),
        file("acceptRide.ts"),
        file("completeRide.ts"),
        file("cancelRide.ts"),
        file("rateRide.ts"),
        file("matchDriver.ts"),
        file("computeFare.ts"),
      ]),
      f("payments", [
        file("mtnMomoCollection.ts"),
        file("mtnMomoWebhook.ts"),
        file("airtelMoneyCollection.ts"),
        file("airtelMoneyWebhook.ts"),
        file("stripePaymentIntent.ts"),
        file("stripeWebhook.ts"),
        file("splitDriverPayout.ts"),
        file("refundPayment.ts"),
      ]),
      f("admin", [
        file("approveDriver.ts"),
        file("suspendUser.ts"),
        file("exportReport.ts"),
        file("broadcastNotice.ts"),
      ]),
      f("utils", [
        file("validatePhoneNumber.ts"),
        file("geoUtils.ts"),
        file("rateLimiter.ts"),
        file("errorHandler.ts"),
      ]),
    ]),
  ]),
  f("src", [
    file("main.tsx"),
    file("App.tsx"),
    file("vite-env.d.ts"),
    file("index.css"),
    f("config", [
      file("firebase.ts"),
      file("environment.ts"),
      file("constants.ts"),
      file("routes.ts"),
      file("featureFlags.ts"),
    ]),
    f("types", [
      file("index.ts"),
      file("user.ts"),
      file("ride.ts"),
      file("driver.ts"),
      file("payment.ts"),
      file("vehicle.ts"),
      file("location.ts"),
      file("notification.ts"),
      file("api.ts"),
      file("enums.ts"),
    ]),
    f("lib", [
      file("utils.ts"),
      file("format.ts"),
      file("validators.ts"),
      file("geo.ts"),
      file("currency.ts"),
      file("permissions.ts"),
    ]),
    f("services", [
      f("api", [
        file("client.ts"),
        file("interceptors.ts"),
        file("endpoints.ts"),
      ]),
      f("auth", [
        file("AuthService.ts"),
        file("PhoneAuthService.ts"),
        file("TokenManager.ts"),
      ]),
      f("firestore", [
        file("FirestoreService.ts"),
        file("UserService.ts"),
        file("RideService.ts"),
        file("DriverService.ts"),
        file("PaymentService.ts"),
        file("VehicleService.ts"),
        file("RatingService.ts"),
        file("NotificationService.ts"),
        file("LocationService.ts"),
      ]),
      f("maps", [
        file("GoogleMapsService.ts"),
        file("PlacesService.ts"),
        file("DirectionsService.ts"),
        file("GeocodingService.ts"),
        file("DistanceMatrixService.ts"),
      ]),
      f("payments", [
        file("MtnMomoService.ts"),
        file("AirtelMoneyService.ts"),
        file("StripeService.ts"),
        file("PaymentRouter.ts"),
        file("WalletService.ts"),
      ]),
      f("notifications", [
        file("PushNotificationService.ts"),
        file("SmsService.ts"),
        file("InAppNotificationService.ts"),
      ]),
    ]),
    f("hooks", [
      file("useAuth.ts"),
      file("useRide.ts"),
      file("useDriver.ts"),
      file("useLocation.ts"),
      file("usePayment.ts"),
      file("useFirestoreSubscription.ts"),
      file("useGeolocation.ts"),
      file("useDebounce.ts"),
      file("useAsync.ts"),
      file("useLocalStorage.ts"),
      file("useMediaQuery.ts"),
      file("usePrevious.ts"),
      file("useToast.ts"),
      file("usePermissions.ts"),
      file("useOnlineStatus.ts"),
    ]),
    f("contexts", [
      file("AuthContext.tsx"),
      file("RideContext.tsx"),
      file("LocationContext.tsx"),
      file("ThemeContext.tsx"),
      file("NotificationContext.tsx"),
      file("WalletContext.tsx"),
      file("ToastContext.tsx"),
    ]),
    f("providers", [
      file("AppProviders.tsx"),
      file("FirebaseProvider.tsx"),
      file("MapsProvider.tsx"),
      file("ThemeProvider.tsx"),
    ]),
    f("store", [
      file("index.ts"),
      f("slices", [
        file("authSlice.ts"),
        file("rideSlice.ts"),
        file("mapSlice.ts"),
        file("paymentSlice.ts"),
        file("uiSlice.ts"),
      ]),
      f("middleware", [
        file("logger.ts"),
        file("errorReporter.ts"),
      ]),
    ]),
    f("components", [
      f("ui", [
        file("button.tsx"),
        file("card.tsx"),
        file("input.tsx"),
        file("label.tsx"),
        file("badge.tsx"),
        file("avatar.tsx"),
        file("dialog.tsx"),
        file("drawer.tsx"),
        file("sheet.tsx"),
        file("select.tsx"),
        file("tabs.tsx"),
        file("toast.tsx"),
        file("tooltip.tsx"),
        file("popover.tsx"),
        file("dropdown-menu.tsx"),
        file("skeleton.tsx"),
        file("spinner.tsx"),
        file("progress.tsx"),
        file("separator.tsx"),
        file("scroll-area.tsx"),
        file("switch.tsx"),
        file("checkbox.tsx"),
        file("radio-group.tsx"),
        file("slider.tsx"),
        file("alert.tsx"),
        file("alert-dialog.tsx"),
        file("accordion.tsx"),
        file("calendar.tsx"),
        file("table.tsx"),
      ]),
      f("shared", [
        file("Logo.tsx"),
        file("BrandMark.tsx"),
        file("AppHeader.tsx"),
        file("AppSidebar.tsx"),
        file("BottomNav.tsx"),
        file("PageContainer.tsx"),
        file("SectionTitle.tsx"),
        file("EmptyState.tsx"),
        file("ErrorBoundary.tsx"),
        file("LoadingScreen.tsx"),
        file("ProtectedRoute.tsx"),
        file("RoleGuard.tsx"),
        file("VersionBadge.tsx"),
        file("NetworkStatusBanner.tsx"),
        file("LanguageSwitcher.tsx"),
        file("ThemeToggle.tsx"),
        file("ConfirmDialog.tsx"),
        file("SearchInput.tsx"),
        file("DataStateWrapper.tsx"),
        file("Pagination.tsx"),
      ]),
      f("maps", [
        file("MapView.tsx"),
        file("MapPicker.tsx"),
        file("DriverMarker.tsx"),
        file("UserMarker.tsx"),
        file("RoutePolyline.tsx"),
        file("NearbyDriversLayer.tsx"),
        file("MapControls.tsx"),
        file("MapLegend.tsx"),
        file("PlaceAutocomplete.tsx"),
        file("StaticMapThumb.tsx"),
      ]),
      f("ride", [
        file("RideRequestForm.tsx"),
        file("RideCard.tsx"),
        file("RideStatusBadge.tsx"),
        file("RideTimeline.tsx"),
        file("RideFareEstimate.tsx"),
        file("RideProgressSheet.tsx"),
        file("DriverArrivalCard.tsx"),
        file("TripSummaryCard.tsx"),
        file("RatingDialog.tsx"),
        file("CancelRideDialog.tsx"),
        file("VehicleClassSelector.tsx"),
        file("FareBreakdownSheet.tsx"),
        file("PromoCodeInput.tsx"),
      ]),
      f("driver", [
        file("DriverCard.tsx"),
        file("DriverStatusToggle.tsx"),
        file("DriverEarningsCard.tsx"),
        file("DriverShiftTimer.tsx"),
        file("IncomingRideAlert.tsx"),
        file("DriverVehicleInfo.tsx"),
        file("DriverRatingSummary.tsx"),
        file("DriverOnboardingSteps.tsx"),
        file("DriverWeeklyStats.tsx"),
      ]),
      f("payment", [
        file("PaymentMethodSelector.tsx"),
        file("MtnMomoInput.tsx"),
        file("AirtelMoneyInput.tsx"),
        file("CardPaymentInput.tsx"),
        file("WalletBalanceCard.tsx"),
        file("TransactionItem.tsx"),
        file("TransactionList.tsx"),
        file("PaymentReceiptSheet.tsx"),
        file("TopUpSheet.tsx"),
        file("PaymentStatusPill.tsx"),
      ]),
      f("charts", [
        file("EarningsChart.tsx"),
        file("RidesChart.tsx"),
        file("FleetUtilizationChart.tsx"),
        file("RevenueByCityChart.tsx"),
        file("ChartContainer.tsx"),
        file("ChartTooltip.tsx"),
      ]),
      f("tables", [
        file("DataTable.tsx"),
        file("RidesTable.tsx"),
        file("DriversTable.tsx"),
        file("UsersTable.tsx"),
        file("TransactionsTable.tsx"),
        file("TableToolbar.tsx"),
        file("TableFilters.tsx"),
      ]),
      f("forms", [
        file("PhoneInput.tsx"),
        file("OtpInput.tsx"),
        file("ProfileForm.tsx"),
        file("VehicleForm.tsx"),
        file("SupportTicketForm.tsx"),
        file("FormField.tsx"),
      ]),
    ]),
    f("features", [
      f("auth", [
        file("LoginPage.tsx"),
        file("RegisterPage.tsx"),
        file("PhoneVerifyPage.tsx"),
        file("ForgotPasswordPage.tsx"),
        file("RoleSelectionPage.tsx"),
        file("LogoutPage.tsx"),
      ]),
      f("passenger", [
        file("PassengerLayout.tsx"),
        file("PassengerHomePage.tsx"),
        file("RequestRidePage.tsx"),
        file("TrackRidePage.tsx"),
        file("RideHistoryPage.tsx"),
        file("RideDetailPage.tsx"),
        file("SavedPlacesPage.tsx"),
        file("PromotionsPage.tsx"),
        file("PassengerProfilePage.tsx"),
        file("PassengerWalletPage.tsx"),
        file("SupportPage.tsx"),
        file("ScheduleRidePage.tsx"),
      ]),
      f("driver", [
        file("DriverLayout.tsx"),
        file("DriverDashboardPage.tsx"),
        file("DriverOnlinePage.tsx"),
        file("IncomingRidesPage.tsx"),
        file("ActiveRidePage.tsx"),
        file("DriverEarningsPage.tsx"),
        file("DriverHistoryPage.tsx"),
        file("DriverProfilePage.tsx"),
        file("VehicleRegistrationPage.tsx"),
        file("DriverRequirementsPage.tsx"),
        file("DriverPayoutsPage.tsx"),
        file("DriverSupportPage.tsx"),
      ]),
      f("rider", [
        file("RiderLayout.tsx"),
        file("RiderDashboardPage.tsx"),
        file("RiderFleetPage.tsx"),
        file("RiderDriversPage.tsx"),
        file("RiderEarningsPage.tsx"),
        file("RiderPerformancePage.tsx"),
        file("RiderSettingsPage.tsx"),
      ]),
      f("admin", [
        file("AdminLayout.tsx"),
        file("AdminDashboardPage.tsx"),
        file("AdminUsersPage.tsx"),
        file("AdminDriversPage.tsx"),
        file("AdminRidesPage.tsx"),
        file("AdminPaymentsPage.tsx"),
        file("AdminTransactionsPage.tsx"),
        file("AdminPayoutsPage.tsx"),
        file("AdminPromotionsPage.tsx"),
        file("AdminSupportPage.tsx"),
        file("AdminReportsPage.tsx"),
        file("AdminSettingsPage.tsx"),
        file("AdminAuditLogPage.tsx"),
        file("AdminFleetZonesPage.tsx"),
        file("AdminBroadcastPage.tsx"),
      ]),
      f("onboarding", [
        file("WelcomePage.tsx"),
        file("SafetyIntroPage.tsx"),
        file("PaymentSetupPage.tsx"),
        file("DriverOnboardingPage.tsx"),
        file("DriverDocumentUploadPage.tsx"),
        file("DriverBackgroundCheckPage.tsx"),
        file("DriverVehicleInspectionPage.tsx"),
      ]),
      f("support", [
        file("HelpCenterPage.tsx"),
        file("SafetyCenterPage.tsx"),
        file("EmergencyContactsPage.tsx"),
        file("ReportIncidentPage.tsx"),
        file("LiveChatWidget.tsx"),
      ]),
      f("settings", [
        file("SettingsLayout.tsx"),
        file("AccountSettingsPage.tsx"),
        file("NotificationSettingsPage.tsx"),
        file("PrivacySettingsPage.tsx"),
        file("LanguageSettingsPage.tsx"),
        file("AppearanceSettingsPage.tsx"),
      ]),
    ]),
    f("layouts", [
      file("RootLayout.tsx"),
      file("AuthLayout.tsx"),
      file("DashboardLayout.tsx"),
      file("MobileLayout.tsx"),
      file("SplitViewLayout.tsx"),
    ]),
    f("routes", [
      file("AppRouter.tsx"),
      file("PassengerRoutes.tsx"),
      file("DriverRoutes.tsx"),
      file("RiderRoutes.tsx"),
      file("AdminRoutes.tsx"),
      file("PublicRoutes.tsx"),
      file("lazyImports.ts"),
    ]),
    f("pages", [
      file("LandingPage.tsx"),
      file("NotFoundPage.tsx"),
      file("ServerErrorPage.tsx"),
      file("OfflinePage.tsx"),
      file("MaintenancePage.tsx"),
    ]),
    f("utils", [
      file("distance.ts"),
      file("fare.ts"),
      file("time.ts"),
      file("phone.ts"),
      file("id.ts"),
      file("mask.ts"),
      file("download.ts"),
      file("analytics.ts"),
      file("errorCodes.ts"),
      file("retry.ts"),
    ]),
    f("i18n", [
      file("config.ts"),
      file("i18n.ts"),
      f("locales", [
        file("en.json"),
        file("sw.json"),
        file("lg.json"),
        file("fr.json"),
      ]),
    ]),
    f("styles", [
      file("globals.css"),
      file("themes.css"),
      file("animations.css"),
    ]),
    f("assets", [
      f("icons", [
        file("index.ts"),
        file("car.tsx"),
        file("moto.tsx"),
        file("boda.tsx"),
      ]),
      f("illustrations", [
        file("empty-rides.svg"),
        file("no-driver.svg"),
        file("payment-success.svg"),
      ]),
    ]),
  ]),
  f("tests", [
    f("unit", [
      f("services", [
        file("RideService.test.ts"),
        file("PaymentService.test.ts"),
        file("MtnMomoService.test.ts"),
        file("AirtelMoneyService.test.ts"),
      ]),
      f("utils", [
        file("fare.test.ts"),
        file("distance.test.ts"),
        file("phone.test.ts"),
      ]),
      f("hooks", [
        file("useAuth.test.ts"),
        file("useRide.test.ts"),
      ]),
    ]),
    f("integration", [
      file("rideFlow.test.tsx"),
      file("paymentFlow.test.tsx"),
      file("authFlow.test.tsx"),
    ]),
    f("e2e", [
      file("passenger-request-ride.spec.ts"),
      file("driver-accept-ride.spec.ts"),
      file("momo-payment.spec.ts"),
    ]),
    f("fixtures", [
      file("users.ts"),
      file("rides.ts"),
      file("drivers.ts"),
      file("payments.ts"),
    ]),
    file("setup.ts"),
  ]),
  file(".env.example"),
  file(".env.local"),
  file(".env.production"),
  file(".eslintrc.cjs"),
  file(".prettierrc"),
  file(".gitignore"),
  file(".editorconfig"),
  file("firebase.json"),
  file("firestore.rules"),
  file("firestore.indexes.json"),
  file("storage.rules"),
  file("database.rules.json"),
  file("vite.config.ts"),
  file("tsconfig.json"),
  file("tsconfig.node.json"),
  file("tailwind.config.ts"),
  file("postcss.config.js"),
  file("package.json"),
  file("pnpm-lock.yaml"),
  file("README.md"),
  file("LICENSE"),
  file("Dockerfile"),
  file("docker-compose.yml"),
  file(".nvmrc"),
]);